fixtures:
  forge_modules:
    augeasproviders_core: 'herculesteam-augeasproviders_core'
    augeasproviders_shellvar: 'herculesteam-augeasproviders_shellvar'
    archive: 'camptocamp-archive'
    concat: 'puppetlabs-concat'
    inifile: 'puppetlabs-inifile'
    stdlib: 'puppetlabs-stdlib'
    systemd: 'camptocamp-systemd'
  symlinks:
    tomcat: "#{source_dir}"
